version: '2.1'

services:
# Start messaging broker
  rabbitmq:
    image: rabbitmq:3.6.5-management
    container_name: open-ocr-mq
    ports:
      - "15672:15672" #Management Server
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"
    healthcheck:
      test: "nc -z localhost 5672"

  # Start OCR worker
  openocrworker:
    image: open-ocr:build
    build:
      context: ./open-ocr
    container_name: open-ocr-worker
    volumes:
      - ./scripts/:/opt/open-ocr/:ro
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    command: "/usr/bin/open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/"

  # Start http server
  openocr:
    image: open-ocr:build
    build:
      context: ./open-ocr
    container_name: open-ocr-httpd
    volumes:
      - ./scripts/:/opt/open-ocr/:ro
    ports:
      - "9292:9292"
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    command: "/usr/bin/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292"
